FROM ruby:3.4.5-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential git libvips libyaml-dev sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

ENV RAILS_ENV=development
EXPOSE 3000

CMD ["bin/rails", "server", "-b", "0.0.0.0"]

